---
- hosts: localhost
  become_user: mclegg 
  become: yes

  tasks:
  - name: Install base packages (zsh, tmux, vim, lldpd, wget)
    community.general.homebrew:
      name: ['zsh','tmux','vim','lldpd','wget']
      state: present 

  - name: Install oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    ignore_errors: yes
 
  - name: Change shell to zsh
    shell: chsh -s $(which zsh)
    become_user: root
    become: yes

  - name: Base16-Shell
    shell: git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
    ignore_errors: yes

  - name: create .ssh directory
    file:
      path: /Users/mclegg/.ssh
      state: directory

  # Generate SSH keypair for Github
  - openssh_keypair:
      path: /Users/mclegg/.ssh/id_ssh_rsa
      size: 4096
      comment: 47733808+jihomc@users.noreply.github.com
  
#  - name: Copy ssh key to clipboard
#    shell: xclip -sel clip < ~/.ssh/id_ssh_rsa.pub

  - name: Git clone dotfiles and copy to home folder
    shell: |
      git clone https://github.com/jihomc/dotfiles.git ~/dotfiles
      cd ~/dotfiles
      cp .zshrc .vimrc .tmux.conf ../

  - name: Set remote git url to ssh
    shell: git remote set-url origin git@github.com:jihomc/dotfiles.git
    args:
      chdir: ~/dotfiles

  - name: Download vim-plug
    shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  - name: Use vim-plug to install base16-vim from .vimrc
    expect:
      command: vim +'PlugInstall --sync' +qa
      responses:
        (?i)Error*: "Enter"
    ignore_errors: yes

  - name: Copy base16-vim colors folder to .vim 
    shell: cp -r ~/.vim/plugged/base16-vim/colors ~/.vim/colors

  - name: Restart terminal
    shell: exec zsh

  - name: Launch lldpd service
    shell: brew services start lldpd
    become: yes

  - pause:
      prompt: "Paste SSH key from clipboard into Github settings, then press ENTER"

